// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Modules.Users.Persistence.Migrations
{
    public partial class UpdateTrainerRoleName : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                schema: "users",
                table: "roles",
                keyColumn: "id",
                keyValue: 2,
                column: "name",
                value: "Trainer");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                schema: "users",
                table: "roles",
                keyColumn: "id",
                keyValue: 2,
                column: "name",
                value: "Coach");
        }
    }
}
