// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Modules.Users.Persistence.Migrations
{
    public partial class UpdateTrainingPermissions : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                schema: "users",
                table: "permissions",
                keyColumn: "id",
                keyValue: 100,
                column: "name",
                value: "ReadUser");

            migrationBuilder.UpdateData(
                schema: "users",
                table: "permissions",
                keyColumn: "id",
                keyValue: 101,
                column: "name",
                value: "ModifyUser");

            migrationBuilder.UpdateData(
                schema: "users",
                table: "permissions",
                keyColumn: "id",
                keyValue: 200,
                columns: new[] { "description", "name" },
                values: new object[] { "Can read invitations.", "ReadInvitations" });

            migrationBuilder.InsertData(
                schema: "users",
                table: "permissions",
                columns: new[] { "id", "description", "name" },
                values: new object[,]
                {
                    { 201, "Can cancel invitation.", "CancelInvitation" },
                    { 202, "Can invite new client.", "InviteClient" }
                });

            migrationBuilder.InsertData(
                schema: "users",
                table: "role_permissions",
                columns: new[] { "permission_id", "role_id" },
                values: new object[,]
                {
                    { 201, 2 },
                    { 202, 2 }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DeleteData(
                schema: "users",
                table: "role_permissions",
                keyColumns: new[] { "permission_id", "role_id" },
                keyValues: new object[] { 201, 2 });

            migrationBuilder.DeleteData(
                schema: "users",
                table: "role_permissions",
                keyColumns: new[] { "permission_id", "role_id" },
                keyValues: new object[] { 202, 2 });

            migrationBuilder.DeleteData(
                schema: "users",
                table: "permissions",
                keyColumn: "id",
                keyValue: 201);

            migrationBuilder.DeleteData(
                schema: "users",
                table: "permissions",
                keyColumn: "id",
                keyValue: 202);

            migrationBuilder.UpdateData(
                schema: "users",
                table: "permissions",
                keyColumn: "id",
                keyValue: 100,
                column: "name",
                value: "UserRead");

            migrationBuilder.UpdateData(
                schema: "users",
                table: "permissions",
                keyColumn: "id",
                keyValue: 101,
                column: "name",
                value: "UserModify");

            migrationBuilder.UpdateData(
                schema: "users",
                table: "permissions",
                keyColumn: "id",
                keyValue: 200,
                columns: new[] { "description", "name" },
                values: new object[] { "Can invite new client.", "InviteClient" });
        }
    }
}
